### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by rrunner7** [monero-ecosystem/monero-java-rpc#13]
Hi,

I am trying to compile the code but I getting those errors. 
I am using netbeans 9.1 with jdk 1.8.0.66.
Can you please tell me if I am doing something wrong or it is a issue in the code ?

COMPILATION ERROR : 
-------------------------------------------------------------
monero/utils/MoneroUtils.java:[185,59] incompatible types: T cannot be converted to int
monero/utils/MoneroUtils.java:[185,71] incompatible types: T cannot be converted to int
monero/utils/MoneroUtils.java:[185,94] incompatible types: T cannot be converted to int
monero/utils/MoneroUtils.java:[185,106] incompatible types: T cannot be converted to int
monero/utils/MoneroUtils.java:[190,57] incompatible types: T cannot be converted to long
monero/utils/MoneroUtils.java:[190,70] incompatible types: T cannot be converted to long
monero/utils/MoneroUtils.java:[190,94] incompatible types: T cannot be converted to long
monero/utils/MoneroUtils.java:[190,107] incompatible types: T cannot be converted to long

BR,
Martin

**Comment by woodser** [comment]
Interesting that my IDE compiler does not complain but maven does.  Anyway, the issue has been fixed.  Thanks!
