### ISSUE TITLE
Changing the remote wallet.

### ISSUE THREAD

**Issue by CarvalhoLeonardo** [monero-ecosystem/monero-java-rpc#8]
Hello.

   I'm testing an architecture to use in a escrow-like solution, and missed the [open_wallet](https://getmonero.org/resources/developer-guides/wallet-rpc.html#open_wallet) call.

   I've forked and created it, is working on an private testnet. 
   Would you like a pull request for it ?
  
   Regards

**Comment by CarvalhoLeonardo** [comment]
Perfect.

Mind if I create a proper Maven hierarchy on the project?

**Comment by woodser** [comment]
Not at all.  Thanks.

**Comment by CarvalhoLeonardo** [comment]
Please see my "desenv" branch, and evaluate what you see.
:)

I intend to create a little test suite using my local testnet and TestNG.

See ya

**Comment by woodser** [comment]
This issue is resolved.  Thank you :)
